kind: pipeline
name: test
clone:
  depth: 50
trigger:
  branch:
  - master
  event:
  - push
steps:
- name: prepare
  image: docker
  commands:
  - wget https://github.com/mritd/gcrsync/releases/download/v1.3.2/gcrsync_linux_amd64
  - mv gcrsync_linux_amd64 gcrsync
  - chmod +x gcrsync
  - mv gcrsync /usr/local/bin/
  - sleep 5
  - docker ps
