kind: pipeline
name: test
clone:
  depth: 50
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: before_install
  image: golang
  commands:
  - wget https://github.com/mritd/gcrsync/releases/download/v1.3.2/gcrsync_linux_amd64
  - sudo mv gcrsync_linux_amd64 gcrsync
  - chmod +x gcrsync
  - sudo mv gcrsync /usr/local/bin/


